spring.application.name=NSLMotors

# Sunucu Portu
server.port=8080

# --- VERITABANI BAGLANTISI AYARLARI ---
spring.datasource.url=jdbc:postgresql://localhost:5432/nsl_motors_db
spring.datasource.username=postgres
spring.datasource.password=1234

# --- JPA/HIBERNATE AYARLARI (CODE FIRST) ---
# 'update' kullan?yoruz: Entityler olu?turulacak ve DB'ye eklenecek.
spring.jpa.hibernate.ddl-auto=update

# Konsolda SQL sorgular?n? g�rmek i�in
spring.jpa.show-sql=true

# Hibernate'in otomatik olarak PostgreSQL Dialect'i kullanmas?na izin veriyoruz
# Bu, uyar?y? da ortadan kald?r?r.
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Daha �nce ekledi?imiz ge�ici otomasyon hari� tutma sat?r?n? siliyoruz.
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# --- MAIL AYARLARI (DO?RULAMA ?�?N) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=imsbusiness00@gmail.com
spring.mail.password=qeev purt ypdg ficj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true